version: "3.5"
services:
  ssv:
    build:
      context: ssv
      args:
        UPSTREAM_VERSION: v1.2.0
    restart: unless-stopped
    volumes:
      - "data:/data"
      - "ssv-operator:/ssv-operator"
    ports:
      - "12515:12515/tcp"
      - "13515:13515/udp"
      - "14515:14515"
    environment:
      BUILDER_PROPOSALS: "false"
      LOG_LEVEL: info
      EXTRA_OPTS: ""
    image: "ssv.ssv-holesky.dnp.dappnode.eth:0.1.0"
volumes:
  data: {}
  ssv-operator: {}
