version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.2.2
    restart: unless-stopped
    volumes:
      - "operator-data:/data/operator"
    ports:
      - "12515:12515/tcp"
      - "13515:13515/udp"
    environment:
      BUILDER_PROPOSALS: "false"
      LOG_LEVEL: info
      EXTRA_OPTS: ""
    image: "operator.ssv-holesky.dnp.dappnode.eth:0.1.0"
  dkg:
    build:
      context: dkg
      args:
        UPSTREAM_VERSION: v1.2.2
    restart: on-failure
    volumes:
      - "operator-data:/data/operator"
      - "dkg-data:/data/dkg"
    ports:
      - "14515:14515"
    environment:
      LOG_LEVEL: info
      EXTRA_OPTS: ""
    image: "dkg.ssv-holesky.dnp.dappnode.eth:0.1.0"
volumes:
  dkg-data: {}
  operator-data: {}
