version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        OPERATOR_UPSTREAM_VERSION: v1.3.5
    restart: unless-stopped
    volumes:
      - operator-data:/data/operator
    ports:
      - 12515:12515/tcp
      - 13515:13515/udp
    environment:
      BUILDER_PROPOSALS: "false"
      LOG_LEVEL: info
      EXTRA_OPTS: ""
      PRIVATE_KEY_PASS: ""
    image: operator.ssv-holesky.dnp.dappnode.eth:0.1.3
  dkg:
    build:
      context: dkg
      args:
        DGK_UPSTREAM_VERSION: v2.1.0
    restart: on-failure
    volumes:
      - operator-data:/data/operator
      - dkg-data:/data/dkg
    ports:
      - "14515:14515"
    environment:
      LOG_LEVEL: info
      OPERATOR_ID: ""
      EXTRA_OPTS: ""
    image: dkg.ssv-holesky.dnp.dappnode.eth:0.1.3
volumes:
  dkg-data: {}
  operator-data: {}
